export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const REQUEST_RECENT = 'REQUEST_RECENT';
export const REQUEST_DELETE_RECENT = 'REQUEST_DELETE_RECENT';
export const REQUEST_TOP = 'REQUEST_TOP';
