export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESEND_OTP_FORGOT_PASSWORD = 'RESEND_OTP_FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const VERIFY_FORGOT_PASSWORD = 'VERIFY_FORGOT_PASSWORD';
