import {DropDownItem} from 'components/Dropdown';

const companySectors: Array<DropDownItem> = [
  {value: 'OIL_GAS_DRILLING', label: 'Oil Gas Drilling'},
  {value: 'GAS_EQUIPMENT_SERVICES', label: 'Gas Equipment Services'},
  {value: 'INTEGRATED_OIL_GAS', label: 'Integrated Oil Gas'},
  {
    value: 'OIL_GAS_EXPLORATION_PRODUCTION',
    label: 'Oil Gas Exploration Production',
  },
  {value: 'OIL_GAS_REFINING_MARKETING', label: 'Oil Gas Refining Marketing'},
  {
    value: 'OIL_GAS_STORAGE_TRANSPORTATION',
    label: 'Oil Gas Storage Transportation',
  },
  {value: 'COAL_CONSUMABLE_FUELS', label: 'Coal Consumable Fuels'},
  {value: 'COMMODITY_CHEMICALS', label: 'Commodity Chemicals'},
  {value: 'DIVERSIFIED_CHEMICALS', label: 'Diversified Chemicals'},
  {
    value: 'FERTILIZERS_AGRICULTURAL_CHEMICALS',
    label: 'Fertilizers Agricultural Chemicals',
  },
  {value: 'INDUSTRIAL_GASSES', label: 'Industrial Gasses'},
  {value: 'SPECIALITY_CHEMICALS', label: 'Speciality Chemicals'},
  {value: 'CONSTRUCTION_MATERIALS', label: 'Construction Materials'},
  {value: 'METAL_GLASS_CONTAINERS', label: 'Metal Glass Containers'},
  {value: 'PAPER_PACKAGING', label: 'Paper Packaging'},
  {value: 'ALUMINUM', label: 'Aluminum'},
  {value: 'DIVERSIFIED_METALS_MINING', label: 'Diversified Metals Mining'},
  {value: 'COPPER', label: 'Copper'},
  {value: 'GOLD', label: 'Gold'},
  {value: 'PRECIOUS_METALS_MINERALS', label: 'Precious Metals Minerals'},
  {value: 'SILVER', label: 'Silver'},
  {value: 'STEEL', label: 'Steel'},
  {value: 'FOREST_PRODUCTS', label: 'Forest Products'},
  {value: 'PAPER_PRODUCTS', label: 'Paper Products'},
  {value: 'AEROSPACE_DEFENSE', label: 'Aerospace Defense'},
  {value: 'BUILDING_PRODUCTS', label: 'Building Products'},
  {value: 'CONSTRUCTION_ENGINEERING', label: 'Construction Engineering'},
  {
    value: 'ELECTRICAL_COMPONENTS_EQUIPMENT',
    label: 'Electrical Components Equipment',
  },
  {value: 'HEAVY_ELECTRICAL_EQUIPMENT', label: 'Heavy Electrical Equipment'},
  {value: 'INDUSTRIAL_CONGLOMERATES', label: 'Industrial Conglomerates'},
  {
    value: 'CONSTRUCTION_MACHINERY_HEAVY_TRUCKS',
    label: 'Construction Machinery Heavy Trucks',
  },
  {value: 'AGRICULTURAL_FARM_MACHINERY', label: 'Agricultural Farm Machinery'},
  {value: 'INDUSTRIAL_MACHINERY', label: 'Industrial Machinery'},
  {
    value: 'TRADING_COMPANIES_DISTRIBUTORS',
    label: 'Trading Companies Distributors',
  },
  {value: 'COMMERCIAL_PRINTING', label: 'Commercial Printing'},
  {
    value: 'ENVIRONMENTAL_FACILITIES_SERVICES',
    label: 'Environmental Facilities Services',
  },
  {value: 'OFFICE_SERVICES_SUPPLIES', label: 'Office Services Supplies'},
  {value: 'DIVERSIFIES_SUPPER_SERVICES', label: 'Diversifies Supper Services'},
  {value: 'SECURITY_ALARM_SERVICES', label: 'Security Alarm Services'},
  {
    value: 'HUMAN_RESOURCES_EMPLOYMENT_SERVICES',
    label: 'Human Resources Employment Services',
  },
  {
    value: 'RESEARCH_CONSULTING_SERVICES',
    label: 'Research Consulting Services',
  },
  {value: 'AIR_FREIGHT_LOGISTICS', label: 'Air Freight Logistics'},
  {value: 'AIRLINES', label: 'Airlines'},
  {value: 'MARINE', label: 'Marine'},
  {value: 'RAILROADS', label: 'Railroads'},
  {value: 'TRUCKING', label: 'Trucking'},
  {value: 'AIRPORT_SERVICES', label: 'Airport Services'},
  {value: 'HIGHWAYS_RAILTRACKS', label: 'Highways Railtracks'},
  {value: 'MARINE_PORTS_SERVICES', label: 'Marine Ports Services'},
  {value: 'AUTO_PARTS_EQUIPMENT', label: 'Auto Parts Equipment'},
  {value: 'TIRES_RUBBER', label: 'Tires Rubber'},
  {value: 'AUTOMOBILE_MANUFACTURERS', label: 'Automobile Manufacturers'},
  {value: 'MOTORCYCLE_MANUFACTURERS', label: 'Motorcycle Manufacturers'},
  {value: 'CONSUMER_ELECTRONICS', label: 'Consumer Electronics'},
  {value: 'HOME_FURNISHINGS', label: 'Home Furnishings'},
  {value: 'HOMEBUILDING', label: 'Homebuilding'},
  {value: 'HOUSEHOLD_APPLIANCES', label: 'Household Appliances'},
  {value: 'HOUSEWARES_SPECIALTIES', label: 'Housewares Specialties'},
  {value: 'LEISURE_PRODUCTS', label: 'Leisure Products'},
  {
    value: 'APPAREL_ACCESSORIES_LUXURY_GOODS',
    label: 'Apparel Accessories Luxury Goods',
  },
  {value: 'FOOTWARE', label: 'Footware'},
  {value: 'TEXTILES', label: 'Textiles'},
  {value: 'CASINOS_GAMING', label: 'Casinos Gaming'},
  {value: 'HOTELS_RESORTS_CRUISE_LINES', label: 'Hotels Resorts Cruise Lines'},
  {value: 'LEISURE_FACILITIES', label: 'Leisure Facilities'},
  {value: 'RESTAURANTS', label: 'Restaurants'},
  {value: 'EDUCATION_SERVICES', label: 'Education Services'},
  {
    value: 'SPECIALIZED_CONSUMER_SERVICES',
    label: 'Specialized Consumer Services',
  },
  {value: 'DISTRUBUTORS', label: 'Distrubutors'},
  {
    value: 'INTERNET_DIRECT_MARKETING_RETAIL',
    label: 'Internet Direct Marketing Retail',
  },
  {value: 'DEPARTMENT_STORES', label: 'Department Stores'},
  {value: 'GENERAL_MERCHANDISE_STORES', label: 'General Merchandise Stores'},
  {value: 'APPAREL_RETAIL', label: 'Apparel Retail'},
  {value: 'COMPUTER_ELECTRONICS_RETAIL', label: 'Computer Electronics Retail'},
  {value: 'HOME_IMPROVEMENT_RETAIL', label: 'Home Improvement Retail'},
  {value: 'SPECIALTY_STORES', label: 'Specialty Stores'},
  {value: 'AUTOMOTIVE_RETAIL', label: 'Automotive Retail'},
  {value: 'HOME_FURNISHING_RETAIL', label: 'Home Furnishing Retail'},
  {value: 'DRUG_RETAIL', label: 'Drug Retail'},
  {value: 'FOOD_DISTRIBUTORS', label: 'Food Distributors'},
  {value: 'FOOD_RETAIL', label: 'Food Retail'},
  {value: 'HYPERMARKETS_SUPER_CENTERS', label: 'Hypermarkets Super Centers'},
  {value: 'BREWERS', label: 'Brewers'},
  {value: 'DISTILLERS_VINTERS', label: 'Distillers Vinters'},
  {value: 'SOFT_DRINKS', label: 'Soft Drinks'},
  {value: 'AGRICULTURAL_PRODUCTS', label: 'Agricultural Products'},
  {value: 'PACKAGED_FOODS_MEATS', label: 'Packaged Foods Meats'},
  {value: 'TOBACCO', label: 'Tobacco'},
  {value: 'HOUSEHOLD_PRODUCTS', label: 'Household Products'},
  {value: 'PERSONAL_PRODUCTS', label: 'Personal Products'},
  {value: 'HEALTHCARE_EQUIPMENT', label: 'Healthcare Equipment'},
  {value: 'HEALTHCARE_SUPPLIES', label: 'Healthcare Supplies'},
  {value: 'HEALTHCARE_DISTRIBUTORS', label: 'Healthcare Distributors'},
  {value: 'HEALTHCARE_SERVICES', label: 'Healthcare Services'},
  {value: 'HEALTHCARE_FACILITIES', label: 'Healthcare Facilities'},
  {value: 'MANAGED_HEALTHCARE', label: 'Managed Healthcare'},
  {value: 'HEALTHCARE_TECHNOLOGY', label: 'Healthcare Technology'},
  {value: 'BIOTECHNOLOGY', label: 'Biotechnology'},
  {value: 'PHARMECEURICALS', label: 'Pharmeceuricals'},
  {
    value: 'LIFE_SCIENCES_TOOLS_SERVICES',
    label: 'Life Sciences Tools Services',
  },
  {value: 'DIVERSIFIED_BANKS', label: 'Diversified Banks'},
  {value: 'REGIONAL_BANKS', label: 'Regional Banks'},
  {value: 'THRIFTS_MORTGAGE_FINANCE', label: 'Thrifts Mortgage Finance'},
  {
    value: 'OTHER_DIVERSIFIES_FINANCIAL_SERVICES',
    label: 'Other Diversifies Financial Services',
  },
  {value: 'MULTI_SECTOR_HOLDINGS', label: 'Multi Sector Holdings'},
  {value: 'SPECIALIZED_FINANCE', label: 'Specialized Finance'},
  {value: 'CONSUMER_FINANCE', label: 'Consumer Finance'},
  {
    value: 'ASSET_MANAGEMENT_CUSTODY_BANKS',
    label: 'Asset Management Custody Banks',
  },
  {
    value: 'INVESTMENT_BANKING_BROKERAGE',
    label: 'Investment Banking Brokerage',
  },
  {value: 'DIVERSIFIES_CAPITAL_MARKETS', label: 'Diversifies Capital Markets'},
  {value: 'FINANCIAL_EXCHANGES_DATA', label: 'Financial Exchanges Data'},
  {value: 'MORTGAGE_REIT', label: 'Mortgage Reit'},
  {value: 'INSURANCE_BROKERS', label: 'Insurance Brokers'},
  {value: 'LIFE_HEALTH_INSURANCE', label: 'Life Health Insurance'},
  {value: 'MULTI_LINE_INSURANCE', label: 'Multi Line Insurance'},
  {value: 'PROPERTY_CASUALTY_INSURANCE', label: 'Property Casualty Insurance'},
  {value: 'REINSURANCE', label: 'Reinsurance'},
  {
    value: 'IT_CONSULTING_OTHER_SERVICES',
    label: 'It Consulting Other Services',
  },
  {
    value: 'DATA_PROCESSING_OUTSOURCED_SERVICES',
    label: 'Data Processing Outsourced Services',
  },
  {
    value: 'INTERNET_SERVICES_INFRASTRUCTURE',
    label: 'Internet Services Infrastructure',
  },
  {value: 'APPLICATION_SOFTWARE', label: 'Application Software'},
  {value: 'SYSTEMS_SOFTWARE', label: 'Systems Software'},
  {value: 'COMMUNICATIONS_EQUIPMENT', label: 'Communications Equipment'},
  {
    value: 'TECHNOLOGY_HARDWARE_STORAGE_PERIPHERALS',
    label: 'Technology Hardware Storage Peripherals',
  },
  {
    value: 'ELECTRONIC_EQUIPMENT_INSTRUMENTS',
    label: 'Electronic Equipment Instruments',
  },
  {value: 'ELECTRONIC_COMPONENTS', label: 'Electronic Components'},
  {
    value: 'ELECTRONIC_MANUFACTURING_SERVICES',
    label: 'Electronic Manufacturing Services',
  },
  {value: 'TECHNOLOGY_DISTRIBUTORS', label: 'Technology Distributors'},
  {value: 'SEMICONDUCTOR_EQUIPMENT', label: 'Semiconductor Equipment'},
  {value: 'SEMICONDUCTORS', label: 'Semiconductors'},
  {value: 'ALTERNATIVE_CARRIERS', label: 'Alternative Carriers'},
  {
    value: 'INTEGRATED_TELECOMS_SERVICES',
    label: 'Integrated Telecoms Services',
  },
  {value: 'WIRELESS_TELECOMS_SERVICES', label: 'Wireless Telecoms Services'},
  {value: 'ADVSERTISING', label: 'Advsertising'},
  {value: 'BROADCASTING', label: 'Broadcasting'},
  {value: 'CABLE_SATELLITE', label: 'Cable Satellite'},
  {value: 'PUBLISHING', label: 'Publishing'},
  {value: 'MOVIES_ENTERTAINMENT', label: 'Movies Entertainment'},
  {
    value: 'INTERACTIVE_HOME_ENTERTAINMENT',
    label: 'Interactive Home Entertainment',
  },
  {value: 'INTERACTIVE_MEDIA_SERVICES', label: 'Interactive Media Services'},
  {value: 'ELECTRONIC_UTILITIES', label: 'Electronic Utilities'},
  {value: 'GAS_UTILITIES', label: 'Gas Utilities'},
  {value: 'MULTI_UTILITIES', label: 'Multi Utilities'},
  {value: 'WATER_UTILITIES', label: 'Water Utilities'},
  {
    value: 'INDEPENDENT_POWER_PRODUCERS_ENERGY_TRADERS',
    label: 'Independent Power Producers Energy Traders',
  },
  {value: 'RENEWABLE_ELECTRICITY', label: 'Renewable Electricity'},
  {value: 'DIVERSIFIED_REIT', label: 'Diversified Reit'},
  {value: 'INDUSTRIAL_REIT', label: 'Industrial Reit'},
  {value: 'HOTEL_RESORT_REIT', label: 'Hotel Resort Reit'},
  {value: 'OFFICE_REIT', label: 'Office Reit'},
  {value: 'HEALTHCARE_REIT', label: 'Healthcare Reit'},
  {value: 'RESIDENTIAL_REIT', label: 'Residential Reit'},
  {value: 'RETAIL_REIT', label: 'Retail Reit'},
  {value: 'SPECIALIZED_REIT', label: 'Specialized Reit'},
  {
    value: 'DIVERSIFIED_REAL_ESTATE_ACTIVITIES',
    label: 'Diversified Real Estate Activities',
  },
  {
    value: 'REAL_ESTATE_OPERATING_COMPANIES',
    label: 'Real Estate Operating Companies',
  },
  {value: 'REAL_ESTATE_DEVELOPMENT', label: 'Real Estate Development'},
  {value: 'REAL_ESTATE_SERVICES', label: 'Real Estate Services'},
];

export default companySectors;
