export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
export const VERIFY_UPDATE_EMAIL = 'VERIFY_UPDATE_EMAIL';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const VERIFY_UPDATE_PHONE = 'VERIFY_UPDATE_PHONE';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_RESIDENTIAL_ADDRESS = 'UPDATE_RESIDENTIAL_ADDRESS';
